packages/hooks/index.js, packages/hooks/lib/useForceUpdate.js, packages/react-sharedb/src/hooks/observer.js, packages/react-sharedb/src/index.js
=> [hooks] add useForceUpdate hook, [react-sharedb] re-export useForceUpdate

packages/ui/components/Tag/Tag.en.mdx, packages/ui/docs/en.js
=> feat[docs -> Tag]: docs for <Tag /> component

packages/ui/components/forms/TextInput/index.js
https://app.asana.com/0/947878965696173/1185629013163105
=> fix(TextInput): fix description props for textinput

packages/ui/components/forms/Checkbox/index.styl
https://app.asana.com/0/947878965696173/1185629013163107
=> fix(Checkbox): add flex-shrink for label

.prettierrc, packages/babel-plugin-ts-interface-to-json-schema/.gitignore, packages/babel-plugin-ts-interface-to-json-schema/README.md, packages/babel-plugin-ts-interface-to-json-schema/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-ts-interface-to-json-schema/__tests__/index.spec.js, packages/babel-plugin-ts-interface-to-json-schema/index.js, packages/babel-plugin-ts-interface-to-json-schema/package.json
Implemented new babel plugin witch create json-schema for ORM mode of typescript interface with additional comments
=> Implemented new babel plugin witch create json-schema for ORM mode of typescript interface with additional comments.

packages/ui/docs/foundation/colors.mdx, packages/ui/docs/foundation/colors.styl, packages/ui/docs/foundation/index.js
https://trello.com/c/FiDKXJV4/9-foundation-colors-page
=> foundation: colors page

packages/ui/docs/foundation/borderRadius.mdx, packages/ui/docs/foundation/borderRadius.styl, packages/ui/docs/foundation/index.js
https://trello.com/c/Jx5g58S2/5-foundation-border-radius-page
=> foundation: border radius page

packages/babel-plugin-startupjs/moduleMap.json, packages/ui/components/AutoSuggest/index.js, packages/ui/components/AutoSuggest/index.styl
https://app.asana.com/0/1172555053361401/1191967823661329
=> fix(ui): AutoSuggest scroll

packages/ui/components/Pagination/Pagination.ru.mdx
=> added useValue hook to the list of imports

packages/ui/components/Div/Div.en.mdx, packages/ui/components/Div/Div.ru.mdx, packages/ui/components/Div/index.js
=> feat(ui/Div): add prop onLongPress

packages/server/README.md, packages/sharedb-access/README.md, packages/sharedb-access/lib/index.js, packages/sharedb-access/test/testUpdate.mocha.js
Reverts startupjs/startupjs#331
Waiting for publishing @dmapper/permisisons
=> Revert "Added backend and  collection parameters to callback function"

packages/ui/components/Link/Link.en.mdx, packages/ui/components/Link/Link.ru.mdx, packages/ui/components/Link/index.js, packages/ui/components/Link/index.styl
- remove hacks which were the plugs of RNW bugs (on new RNW these bugs is missing)
- update docs
- handle the case when the link is a button
=> refactor(Link)

packages/ui/components/forms/Checkbox/index.js, packages/ui/components/forms/Checkbox/index.styl
=> fix(Checkbox): fix mobile readonly

packages/app/client/components/AccessDeny/index.js, packages/app/client/components/AccessDeny/index.styl, packages/app/client/components/index.js, packages/app/client/index.js, packages/orm/lib/promisifyRacer.js
=> Added catch access error and screen for 'Access deny'

packages/docs/client/components/Props/Constructor/index.js
=> ref(Sandbox): use NumberInput for 'number' props

packages/mdx/client/mdxComponents/index.js
=> fix(docs): fix anchors in inline code headers in mdx files

packages/auth-local/client/components/ChangePasswordForm/index.js, packages/auth-local/client/components/LoginForm/index.js, packages/auth-local/client/components/RecoverForm/index.js, packages/auth-local/client/components/RegisterForm/index.js, packages/auth-local/client/components/ResetPasswordForm/index.js, packages/auth/client/helpers/finishAuth.js
fix(): Add slide name to return values
=> Add redirectUrl param to finish auth helper

packages/ui/components/Modal/index.js
=> fix(ui/Modal): fix fullscreen modal in iOS

packages/ui/components/forms/Multiselect/index.styl, packages/ui/components/forms/Multiselect/multiselect.web.js
https://app.asana.com/0/1172555053361401/1199525903293820
=> fix(ui/Multiselect): fix height

packages/auth-local/client/components/LoginForm/index.js, packages/auth-local/client/components/RegisterForm/index.js, packages/auth/client/components/AuthForm/index.js
https://trello.com/c/nRR0W0lG/282-startupjs-auth-login-register-form-autofill
=> feat(auth) email and name autofill via url

packages/ui/components/Alert/Alert.en.mdx, packages/ui/components/Alert/Alert.ru.mdx, packages/ui/components/Alert/index.js, packages/ui/components/Alert/index.styl
=> ref(ui/Alert): improve Alert

packages/cli/index.js, packages/cli/link/path.js
=> fix(cli): fix android link

packages/ui/components/forms/Multiselect/Multiselect.en.mdx, packages/ui/components/forms/Multiselect/Multiselect.ru.mdx, packages/ui/components/forms/Multiselect/defaultInput.js, packages/ui/components/forms/Multiselect/defaultTag.js, packages/ui/components/forms/Multiselect/index.js, packages/ui/components/forms/Multiselect/index.styl, packages/ui/components/forms/Multiselect/input.js, packages/ui/components/forms/Multiselect/multiselect.js, packages/ui/components/forms/Multiselect/multiselect.web.js
=> feat(ui/Multiselect): add InputComponent prop

packages/ui/components/Menu/MenuItem/index.styl
Фикс проблемы на мобилках - https://bitbucket.org/dmapper/core/pull-requests/207
=> fix(ui/MenuItem): flex grow

packages/ui/components/popups/Popover/Popover.en.mdx, packages/ui/components/popups/Popover/index.js
Bug: smart-table Filter doesn't close when opened through the three-dots-menu.
https://app.asana.com/0/1199640785361653/1199899277818581
=> fix(ui/Popover): multiple popover close bug

docs/migration-guides/0.35.md, packages/ui/components/table/Td/index.styl, packages/ui/components/table/Th/index.styl, packages/ui/components/table/Tr/index.js, packages/ui/components/table/Tr/index.styl
fix(Tr): remove paddings
fix(Td): increase horizontal paddings to 16px
fix(Th): increase horizontal paddings to 16px
=> fix(Table): fix paddings

packages/docs/client/components/Props/Constructor/Td/index.styl, packages/docs/client/components/Props/Constructor/index.js, packages/docs/client/components/Props/Constructor/index.styl
=> feat(docs/Sandbox): add Required prop label

packages/ui/components/typography/Span/index.js, packages/ui/components/typography/Span/index.styl, packages/ui/components/typography/Typography.en.mdx, packages/ui/components/typography/Typography.ru.mdx, packages/ui/components/typography/index.styl, packages/ui/styles/typography.styl, packages/ui/styles/variables.styl
first need to merge https://github.com/startupjs/startupjs/pull/631
=> ref(ui/typography): refactor font() mixin and deprecated Span variants

packages/auth-local/client/components/RecoverForm/index.js, packages/auth-local/client/components/RegisterForm/index.js
Revert because of incorrect commit name
=> Revert "fix(auth-local): fix recaptcha error on cancel"

packages/auth-local/client/components/RecoverForm/index.js
add testID on the recover password page
=> test: add testId on the recover pass page

.github/workflows/main.yml, helm/chart/Chart.yaml, helm/chart/templates/deployment.yaml, helm/chart/templates/ingress.yaml, helm/chart/templates/service.yaml, helm/chart/values.yaml
Full CICD flow to new AKS cluster.
=> Github actions added

packages/ui/components/Carousel/Carousel.en.mdx
https://trello.com/c/KwPDatZx/527-there-is-no-vertical-mode-section-on-the-carousel-page-for-english-version-startup
=> fix(ui/Carousel): en doc vertical mode

packages/ui/components/typography/Typography.en.mdx, packages/ui/components/typography/Typography.ru.mdx
https://trello.com/c/4pIVFO2Q/606-bug-sandbox-there-is-no-data-in-the-sandbox-on-the-typography-components-page-startup
=> fix(typography): fix test children sandbox

packages/ui/components/Card/Card.en.mdx, packages/ui/components/Card/Card.ru.mdx
https://trello.com/c/otzQUWEa/576-card-goes-beyond-the-screen-on-the-components-card-page-for-mobile-version-startup
=> fix(ui/Card): docs media

packages/babel-plugin-i18n-extract/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-i18n-extract/__tests__/__snapshots__/translations.spec.js.snap, packages/babel-plugin-i18n-extract/index.js, packages/babel-plugin-i18n-extract/package.json, packages/i18n/client/t.js, packages/i18n/client/useI18nGlobalInit.js, packages/i18n/client/useLang.js, packages/startupjs/index.js
=> fix(i18n): fix bug in 't' function related to missing filename in key param

packages/ui/components/forms/DateTimePicker/components/TimeSelect/index.js
Task https://trello.com/c/q67HSaMc/1606-bug-start-time-dropdown-has-empty-space-when-the-time-is-finished
=> DateTimePicker: fix layout height

packages/ui/components/forms/Multiselect/index.js, packages/ui/components/forms/Multiselect/index.styl, packages/ui/components/forms/Multiselect/multiselect.web.js
fixed web forms/input/multiselect (removed non-working checkbox, added icon, fixed suggestions scroll)
=> fix web forms/input/multiselect 

packages/auth-local/client/components/RegisterForm/index.js
=> Registration name split bug

packages/auth-local/server/Provider.js, packages/auth-local/server/Strategy.js, packages/auth-local/server/api/register.js, packages/auth/server/BaseProvider.js
Reverts startupjs/startupjs#929
=> Revert "feat(auth): add helpers for providers"

packages/ui/components/forms/Select/Select.en.mdx, packages/ui/components/forms/Select/Select.ru.mdx, packages/ui/components/forms/Select/Wrapper/index.android.js, packages/ui/components/forms/Select/Wrapper/index.ios.js, packages/ui/components/forms/Select/Wrapper/index.web.js, packages/ui/components/forms/Select/index.js
Reverts startupjs/startupjs#938
=> Revert "feat(select): add ability to change empty item label"

packages/ui/components/AbstractPopover/index.js, packages/ui/components/AutoSuggest/index.js
in addition to https://bitbucket.org/dmapper/lingua/pull-requests/3436
=> fix: autoSuggest and abstrackPopover components

packages/ui/components/Row/index.js
=> Row component: fix  mobile bug

docker/deploy-aks/Dockerfile, docker/deploy-aks/README.md, docker/deploy-aks/entrypoint.sh
Feature branches implementation
=> feature branches initial

packages/ui/components/Row/index.js
=> Row component: fix style value

docker/deploy-aks/README.md, docker/deploy-aks/entrypoint.sh
Add support for wildcard certificates for feature branches
=> feature branches wildcard certificate

.github/workflows/run-tests.yaml, .github/workflows/test-e2e.yaml, package.json, test/.eslintrc.json, test/specs/main.e2e.js, wdio.conf.js, yarn.lock
This PR sets up GitHub Actions to run automated tests with WebdriverIO on every push and pull request. MongoDB, Redis, and ChromeDriver are also setup to work together with our Node.js application.
Changes include:
1. Created a new GitHub Actions workflow that:
- Triggers on every push or pull request.
- Sets up a service container for MongoDB and Redis.
- Installs the latest version of Chromium.
- Starts our Node.js application.
- Waits for 10 seconds to ensure the application is ready.
- Executes our WebdriverIO tests.
2. Updated `wdio.conf.js` to:
- Run Chrome in headless mode when inside a CI environment.
3. Added a basic WebdriverIO test to check the homepage of our application.
These changes ensure that our tests are automatically run in a consistent environment, improving the …
=> test: Add E2E tests with WebdriverIO and make Github Action

packages/ui/components/toast/ToastComponent.js, packages/ui/components/toast/index.styl
=> fix toast text and close icon alignment

packages/backend/db/mingo-sqlite.js, packages/create-startupjs/install/index.js, packages/create-startupjs/install/ui-expo/package.json, packages/hooks/lib/useBind.js, packages/server/index.js, packages/server/initServer.auto.js, packages/ui/UiProvider.js, packages/ui/components/dialogs/DialogsProvider.js, packages/ui/components/dialogs/helpers.js, packages/ui/components/dialogs/prompt.js, packages/ui/components/forms/FileInput/constants.js, packages/ui/components/forms/FileInput/files.plugin.js, packages/ui/components/forms/FileInput/index.js, packages/ui/components/forms/FileInput/input.expo.js, packages/ui/components/forms/FileInput/input.js, packages/ui/components/forms/Input/inputs.js, packages/ui/helpers/index.js, packages/ui/helpers/path.js, packages/ui/index.js, packages/ui/package.json, yarn.lock
Add `FileInput` to easily upload files
```jsx
const [fileId, setFileId] = useState()
<Input type='file' value={fileId} onChange={setFileId} />
```
or you can just pass `$value` instead of `value` and `onChange`.
`fileId` will be the id of a document in the `files` collection.
You can get a url to this file the following way:
```jsx
const $file = useDoc$('files', fileId)
return <Avatar src={$file.getUrl()} />
```
`getUrl` - get url to file for showing it as an image etc.
`getDownloadUrl` - same as `getUrl()` but will force downloading the file (at least in the browser)
`getUploadUrl` - url to update this file with a new one
`getDeleteUrl` - url to delete this file
For now only support `sqlite` storage (same one which is used for db) and only support web.
The whole implementation is …
=> feat(ui/FileInput): implement FileInput for uploading files to different storages

packages/babel-plugin-eliminator/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-eliminator/__tests__/index.spec.js, packages/babel-plugin-eliminator/index.js, packages/babel-plugin-eliminator/lib/removeOtherEnvs.js, packages/backend/features/serverAggregate.js, packages/backend/features/validateSchema.js, packages/backend/index.d.ts, packages/backend/index.js, packages/backend/package.json, packages/bundler/lib/eliminatorLoader.js, packages/bundler/metro-babel-transformer.js, packages/orm/lib/index.js, packages/orm/package.json, packages/react-sharedb-hooks/lib/subscriptionTypeFns.js, packages/server-aggregate/server.js, packages/server/index.d.ts, packages/server/index.js, packages/utils/aggregation.js, packages/utils/package.json, tsconfig.json, yarn.lock
Enable `serverAggregate: true` in `features` of `startupjs.config.js`
Then define your aggregations explicitly in your model files in the `model/` folder.
Define an aggregation using this function and export it as a named export const from your model file.
**`params`**
query params passed into
```js
useQuery$($$aggregation, params)
```
or to Racer's model:
```js
model.query($$aggregation.collection, {
$aggregationName: $$aggregation.name,
$params: params
})
```
**`context`**
```js
{
session, // current user's server-side session (usually would have things things like `session.userId`, `session.loggedIn`, etc.)
model, // root model
collection // name of the collection (useful for cases when you want to reuse the same aggregation function across multiple collections in different model …
```
=> feat(orm): simplify api of working with server aggregations

core/server/package.json, core/server/plugins/auth.plugin.js, core/server/utils/clientLogin.js, core/server/utils/clientLogout.js, core/server/utils/clientSessionData.js, core/server/utils/constants.js, core/server/utils/reload.js, core/startupjs/package.json, core/utils/lib/_navigate.expo.js, core/utils/lib/_navigate.js, core/utils/navigate.js, core/utils/navigate.server.js, core/utils/package.json, expoapp/app/auth/login.js, expoapp/startupjs.config.js, yarn.lock
TODO: still need to fix some issues with restarting the native app after login and after logout
=> feat(server): implement local auth.

core/server/package.json, core/server/plugins/auth.plugin.js, yarn.lock
It only needs `APPLE_CLIENT_ID` since Apple sends the token right away and then we check the validity of it separately.
The clientId is the identifier of a Service ID here:
https://developer.apple.com/account/resources/identifiers/list/serviceId
=> feat(server/auth): implement Apple auth
