startupjs/startupjs

packages/routes-middleware/lib/defaultClientLayout.js, packages/routes-middleware/lib/index.js, packages/routes-middleware/lib/reactNativeWeb.css
Add `mode` option which can be:
- `react-native` (default)
- `web`
`react-native` mode makes all root DOM elements fullscreen with flex-direction column and removes scroll (`ScrollView` has to be used in react-native).
When you want a pure web project, specify `{ mode: 'web' }` in `startupjsServer` options.
=> [routes-middleware] Polyfill global react-native-web styles

packages/babel-preset-startupjs/index.js, packages/babel-preset-startupjs/metroWithTypescript.js, packages/babel-preset-startupjs/package.json, packages/bundler/helpers.js, packages/bundler/package.json, packages/bundler/webpack.server.config.js, packages/bundler/webpack.web.config.js, styleguide/tsconfig.json
Use the following instructions to setup TypeScript in your project:
https://reactnative.dev/docs/typescript
You should also add the following option to your `tsconfig.json` in order for the typechecking to work correctly:
```json
"onlyRemoveTypeImports": true,
```
=> Add TypeScript support

packages/init/package.json, packages/init/src/util/common.js, packages/orm/README.md, packages/orm/lib/index.js, packages/orm/lib/promisifyRacer.js
- Promisify modifiers all `Model` modifiers, like `set`, `setEach`, `push`, etc.
- Promisify `subscribe`/`fetch` of `Model` and `Query`
Now we can use everything as described in the racer docs but with `async/await`:
```jsx
observer(function User ({ userId }) {
const [user, $user] = useDoc('users', userId)
if (!user) throw $user.create()
async function updateUserAge (age) {
await $user.setDiff('age', age)
await $user.adjustAgePolicies(age)
alert('Your age and age policies update.')
if (age < 18) {
alert('Content unsafe for children is blocked')
}
}
// render user and an input to update his/her age
})
```
- Deprecate `*Async()` methods on `Model` and `Query`. Regular methods should be used instead.
=> Promisify racer

packages/ui/components/forms/Checkbox/Checkbox.en.mdx, packages/ui/components/forms/Checkbox/Checkbox.ru.mdx, packages/ui/components/forms/Checkbox/index.js, packages/ui/components/forms/Checkbox/index.styl, packages/ui/components/forms/Multiselect/Multiselect.en.mdx, packages/ui/components/forms/Multiselect/index.js, packages/ui/components/forms/Multiselect/index.styl, packages/ui/components/forms/Multiselect/input.js, packages/ui/components/forms/Multiselect/multiselect.web.js, packages/ui/components/forms/Radio/Radio.en.mdx, packages/ui/components/forms/Radio/Radio.ru.mdx, packages/ui/components/forms/Radio/index.js, packages/ui/components/forms/Radio/input.js, packages/ui/components/forms/Select/Select.en.mdx, packages/ui/components/forms/Select/Select.ru.mdx, packages/ui/components/forms/Select/index.js, packages/ui/components/forms/TextInput/TextInput.en.mdx, packages/ui/components/forms/TextInput/TextInput.ru.mdx, packages/ui/components/forms/TextInput/index.js, packages/ui/components/forms/TextInput/index.styl
https://trello.com/c/Kkcllz47/85-ui-add-readonly-to-the-input-fields-and-check-if-disabled-is-everywhere
=> add readOnly prop for inputs

packages/ui/components/Tabs/Tabs.en.mdx, packages/ui/components/Tabs/Tabs.ru.mdx
On the tabs Russian documentation page, the page crashed with an error
=> doc(Tabs): fix error

packages/react-sharedb-hooks/README.md
Use `secret` instead of undefined `code` in example code.
=> readme(react-sharedb-hooks): fix undefined reference in example code

packages/ui/components/Button/index.js
because when the number 0 arrives in the children button, it did not display anything
=> fix(ui/Button): fix check for children button

docs/migration-guides/0.34.md, packages/ui/components/Button/index.js
BREAKING CHANGE: startupjs/ui/Button
- remove `shadowed` from `variant` property
=> feat(Button): remove shadowed from variant property

docs/migration-guides/0.34.md, docs/migration-guides/index.js, packages/ui/components/forms/PasswordInput/PasswordInput.en.mdx, packages/ui/components/forms/PasswordInput/PasswordInput.ru.mdx, packages/ui/components/forms/PasswordInput/index.js, packages/ui/docs/forms.js
BREAKING CHANGE: `startupjs/ui/PasswordInput` - remove `secureTextEntry` property
=> fix(PasswordInput): remove secureTextEntry property

docs/migration-guides/0.34.md, packages/ui/components/Badge/Badge.en.mdx, packages/ui/components/Badge/Badge.ru.mdx, packages/ui/components/Tag/Tag.en.mdx, packages/ui/components/Tag/Tag.ru.mdx, packages/ui/components/Tag/index.js, packages/ui/components/Tag/index.mdx.styl, packages/ui/components/Tag/index.styl, packages/ui/components/forms/Multiselect/defaultTag.js
BREKING CHANGE:
- remove `iconPosition` property. For the icon on the left, use the `icon` property and `iconStyle` to style it, for the icon on the right, use the `secondaryIcon` and `secondaryIconStyle` properties, and all these properties to use two icons
- no more support loading indicator for async action
- the default component size has become larger
- add `size` property
=> Refactor tag

packages/auth/client/helpers/onLogout.js
It fell when invoke onLogout without arguments (like onLogout())
=> fix(auth): add default argument for onLogout

packages/backend/index.js, packages/backend/package.json
1. Implement locking in redis itself for flushing Redis DB once a day.
This should improve stability of production when delpoying.
2. Use prefix for ShareDB PubSub in redis.
This allows having multiple staging apps to use the same Redis DB.
**IMPORTANT:** backend function now also returns `redisPrefix`. You should use it as a prefix for your lock names if you use `redlock` in your business logic. And for any other redis keys you have in your app/libraries.
This is a NON-BREAKING change, **BUT** in our next release we **should** let people know that they should use `redisPrefix` returned from the `backend()` function in all their redis locks (`redlock`).
@Yska We should also:
1. Refactor `worker` to use `redisPrefix` in `redlock` lock names.
2. Refactor `online-status-tracker` (from our …
=> feat(backend): Implement proper flushing of redis db, use prefix for redis keys in sharedb

.github/workflows/docker.yaml, docker/deploy-aks/Dockerfile, docker/deploy-aks/README.md, docker/deploy-aks/entrypoint.sh, docker/deploy-aks/sample-cicd/github-workflow.yml
implement a fully universal docker container to build and deploy the startupjs app to an opinionated AKS cluster.
It uses `kaniko` under the hood to build an image in any `docker` runtime, so you can use docker binary of any CI/CD provider or Kubernetes or your local Docker.
1. You must provide a service principal key `AZURE_CREDENTIALS` which has access to only one resource group which has only one AKS cluster and only one ACR. It doesn't matter how you name them.
2. Deployments which you want to update in this cluster must have the following labels in `metadata.labels`:
```
managed-by=terraform
part-of=${APP}
```
Replace ${APP} with the name of your app, for example `part-of=myapp`
3. Container name inside the Deployment (`spec.template.spec.containers[0].name`) must be the same as the …
=> feat(deploy): Implement universal docker container for CI/CD to deploy to AKS

packages/cli/index.js
This commit fixes the problem:
Oops! Something went wrong! :(
ESLint: 8.32.0
ESLint couldn't find the plugin "eslint-plugin-react-hooks".
(The package "eslint-plugin-react-hooks" was not found when loaded as a Node module from the directory "/Users/alex/Work/DM/gilleslist".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
npm install eslint-plugin-react-hooks@latest --save-dev
The plugin "eslint-plugin-react-hooks" was referenced from the config file in ".eslintrc.json » eslint-config-standard-react".
=> fix(cli): Added eslint-plugin-react-hooks to devDeps template

packages/server/server/index.js
=> fix(server): accept correct arguments in gracefulShutdown fn

packages/ui/components/forms/DateTimePicker/index.js
Try to use `style` prop before changes:
- expected: override input style
- [-] actual result: override input's parent div style (wrapper) ![image](https://github.com/startupjs/startupjs/assets/17129937/47c298dd-117d-4d17-8165-51da46ee5644)
Try to use `inputStyle` prop before changes:
- expected: override input style
- [-] actual result: override input's parent div style (wrapper) ![image](https://github.com/startupjs/startupjs/assets/17129937/28a3e2f6-c632-4af2-800d-fee6c0629597)
Try to use `inputStyle` prop after changes:
- expected: override input style
=> DateTimePicker component styles #1168

expoapp/app/(tabs)/index.tsx, expoapp/app/(tabs)/three.js, expoapp/app/(tabs)/two.tsx, packages/babel-plugin-startupjs-plugins/loader.js, packages/init/lib/native/index.js, packages/registry/createRegistry.js, packages/registry/lib/Module.js, packages/registry/lib/Plugin.js, packages/registry/lib/Registry.js, packages/registry/lib/sortPlugins.js, packages/server/package.json, packages/server/plugins/clientSession.plugin.js, packages/utils/axios.cjs, packages/utils/axios.d.ts, packages/utils/axios.js, packages/utils/axios.server.cjs, packages/utils/package.json
- Handle cases when the plugin is initially disabled.
- Support function in 'enabled' setting of plugin to dynamically decide whether to enable the plugin before initialization.
- Add 'clientSession' plugin which passes the model's '_session' from server to the client.
- Specify a particular `axios` dist file (browser one) for our axios reexport, since the default 'axios' import doesn't resolve correctly for some reason on ios and resolves to 'node' variant instead.
=> feat(registry): support delayed initialization of plugins. feat(server): add 'clientSession' plugin.

expoapp/model/testCounts.[id].mjs, expoapp/startupjs.config.mjs, packages/babel-plugin-startupjs-plugins/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-startupjs-plugins/__tests__/index.spec.js, packages/babel-plugin-startupjs-plugins/fixtures/model/_session.games.[id].js, packages/babel-plugin-startupjs-plugins/fixtures/model/_session.games.js, packages/babel-plugin-startupjs-plugins/fixtures/model/users.[id].js, packages/babel-plugin-startupjs-plugins/fixtures/model/users.js, packages/babel-plugin-startupjs-plugins/fixtures/node_modules/config/index.js, packages/babel-plugin-startupjs-plugins/index.js, packages/babel-plugin-startupjs-plugins/loader.js, packages/bundler/metro-config.js, packages/registry/createRegistry.js, packages/registry/index.js, packages/registry/loadStartupjsConfig.js, packages/registry/virtual/startupjs.config.virtual.js, packages/registry/virtual/startupjs.models.virtual.js, packages/registry/virtual/startupjs.plugins.virtual.js, packages/startupjs/templates/simple/startupjs.config.js, styleguide/startupjs.config.js
Implement file-system model loading.
Automatically scan `model` folder in the project's root and load all model from there.
Model filesnames must be named as the pattern which will be used for loading.
Instead of `*` use `[id]`, for example:
```
/model
users.js
users.[id].js
_session.games.js
_session.games.[id].js
```
=> feat(orm): Autoload orm models from 'model' folder

packages/ui/components/Layout/index.js, packages/ui/components/Link/index.js, packages/ui/hooks/useRouter.expo.js, packages/ui/hooks/useRouter.js, packages/ui/package.json, yarn.lock
- remove direct dependency on `react-router-web` and `react-router-native` - use `react-router` instead and as a peerDependency.
- add support for 'expo-router'
=> fix(ui/Link): abstract away usage of router to support both expo-router and react-router

packages/babel-plugin-rn-stylename-to-style/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-rn-stylename-to-style/__tests__/index.spec.js, packages/babel-plugin-rn-stylename-to-style/index.cjs, packages/babel-plugin-rn-stylename-to-style/package.json, yarn.lock
Support manually executing `styl()` and `css()` functions to get the same result as from transforming the `styleName` in JSX.
This is useful when you need to programmatically generate styles following the same principles as in JSX transformation.
Instead of preprocessing things through `styleName`:
```jsx
import './index.styl'
const Test = ({
style, active, variant, cardStyle: myCardStyle,
contentStyle, title, ...props
}) => {
function render () {
return (
<Card
styleName={['root', variant]}
style={[myCardStyle, { color: 'blue' }]}
titleStyle={{ color: 'red' }}
>
<Content styleName={['content', variant, { active }]} />
</Card>
)
}
return render()
}
```
You can manually execute the style props generation using `styl()` as a function:
```jsx
import './index.styl'
import { styl } from …
```
=> feat(babel-plugin-rn-stylename-to-style): support styl(), css() functions which manually returns styles same way as styleName

expoapp/app/(tabs)/three.js, packages/babel-plugin-startupjs-plugins/README.md, packages/babel-plugin-startupjs-plugins/__tests__/__snapshots__/index.spec.js.snap, packages/babel-plugin-startupjs-plugins/__tests__/index.spec.js, packages/babel-plugin-startupjs-plugins/fixtures/model/index.js, packages/babel-plugin-startupjs-plugins/index.js, packages/babel-plugin-startupjs-plugins/loader.js, packages/bundler/lib/eliminatorLoader.js, packages/bundler/metro-babel-transformer.js
on Metro when handling the virtual model folder import it's now transformed into `require.context` (which follows Webpack spec).
So now if you create the `model` folder and add files to it -- it will dynamically add them and reload the page.
on Node we load as usual (will add some workaround later for dynamically updating models on Node too).
Also, handle `/model/index.js` file as the root model.
=> fix(babel-plugin-startupjs-plugins): Use `require.context` on Metro to dynamically load `/model` folder with hot-reloading

packages/ui/components/forms/Form/index.js, packages/ui/components/forms/Form/useValidate.js, packages/ui/index.d.ts, packages/ui/index.js, packages/ui/package.json
By default `Form` does not run any validation.
By passing `validate=true` it will validate always.
```js
<Form validate={true} />
```
To trigger validation manually, use `useValidate()` hook.
It will return the `validate` function which you can call manually to run the validation. It will return `true` if validation has passed (there are NO errors).
If there are errors, they will be available in `validate.hasErrors` (`true` or `false`) and `validate.errors` (errors themselves as an object of field names and an array of errors: `{ name: ['This field is required'], age: ['must be above 18'] }`)
By default, only after the first manual `validate()` call the `Form` will start showing errors and update them reactively (on each change to the form).
If you want the `Form` to start showing errors …
=> feat(ui/Form): Simplify api to validate the form - useValidate() and Form(validate)

packages/utils/lib/getBaseUrl.expo.js
Explicitly specifying baseUrl is only required for the production builds of ios and android.
In order to specify the explicit baseUrl, you have to make sure `EXPO_PUBLIC_BASE_URL`
env variable is set in your environment during the build time.
For production builds it means you'll run the following commands:
- android:
EXPO_PUBLIC_BASE_URL=https://myapp.com npx expo run:android --variant release
- ios:
EXPO_PUBLIC_BASE_URL=https://myapp.com npx expo run:ios --configuration Release
**IMPORTANT:**
- The production build commands above for android and ios are NOT automatically
code signed for submission to the Google Play Store and Apple App Store.
They are just for the local testing of the production build.
To generate an actual production build for submission to the app stores,
refer to the …
=> feat(startupjs): support setting explicit BASE_URL via EXPO_PUBLIC_BASE_URL env var

core/ui/components/popups/Drawer/index.js, core/ui/components/popups/Drawer/index.styl
=> fix(popups/Drawer): removes redundant z-index from elements

core/server/plugins/auth.plugin.js, core/server/utils/clientLogin.js, core/server/utils/constants.js, expoapp/app/auth/login.js
provider name is `force`
For a simple usecase which is implemented by default you'll need to do the following:
1. set `FORCE_CLIENT_SECRET` to a secret token
2. make a way in you app for users to set this secret token into their `auth` document: `$.auths[userId].force.token.set(token)`
In a real app you would want to change the `validateAccess` function and check if the user has admin rights:
```js
force: {
async validateAccess ({ session }) {
if (!await isAdmin(session.userId)) throw Error('Only admins can do it')
}
}
```
Or if you want to let only particular managers to log into users they are responsible for, you can do something like the following:
```js
force: {
async validateAccess ({ session, targetUserId }) {
if (!await isManagerOf(session.userId, targetUserId)) {
const err = …
```
=> feat(server/auth): add 'Login as...' provider to be used by trusted users

core/ui/components/Modal/ModalHeader/index.styl
=> fix: header title on mobile

core/ui/components/forms/FileInput/providers/azureblob.js
Azure Blob Storage does not allow containers 2 chars length.
=> FileInput: Azure error fixed
